import { SubtitleProject, SubtitleSegment } from '../types/subtitle';

export const DEMO_SEGMENTS: SubtitleSegment[] = [
  {
    id: 1,
    start: 2.15,
    end: 6.8,
    original: 'مَثَلُهُمْ كَمَثَلِ الَّذِي اسْتَوْقَدَ نَارًا',
    translations: {
      id: 'Perumpamaan mereka seperti orang yang menyalakan api',
      en: 'Their example is that of one who kindled a fire',
      ms: 'Perbandingan mereka sama seperti orang yang menyalakan api',
      fr: 'Leur exemple est semblable à celui qui a allumé un feu',
      ur: 'ان کی مثال اس شخص کی سی ہے جس نے آگ جلائی',
    },
    verseNumber: 17,
    isAiGeneratedOriginal: false,
  },
  {
    id: 2,
    start: 6.85,
    end: 12.4,
    original: 'فَلَمَّا أَضَاءَتْ مَا حَوْلَهُ ذَهَبَ اللَّهُ بِنُورِهِمْ',
    translations: {
      id: 'Ketika api itu menerangi sekelilingnya, Allah menghilangkan cahaya mereka',
      en: 'When it illuminated what was around him, Allah took away their light',
      ms: 'Tatkala api itu menerangi sekelilingnya, Allah melenyapkan cahaya mereka',
      fr: "Puis, quand elle a illuminé tout à l'entour, Allah a emporté leur lumière",
      ur: 'جب آگ نے اردگرد کو روشن کیا تو اللہ نے ان کا نور چھین لیا',
    },
    verseNumber: 17,
    isAiGeneratedOriginal: false,
  },
  {
    id: 3,
    start: 12.45,
    end: 17.6,
    original: 'وَتَرَكَهُمْ فِي ظُلُمَاتٍ لَّا يُبْصِرُونَ',
    translations: {
      id: 'Dan membiarkan mereka dalam kegelapan, tidak dapat melihat',
      en: 'And left them in darkness [so] they could not see',
      ms: 'Dan membiarkan mereka dalam kegelapan yang tidak dapat melihat',
      fr: 'Et les a laissés dans les ténèbres où ils ne voient plus rien',
      ur: 'اور انہیں اندھیروں میں چھوڑ دیا کہ کچھ سجھائی نہیں دیتا',
    },
    verseNumber: 17,
    isAiGeneratedOriginal: false,
  },
  {
    id: 4,
    start: 17.9,
    end: 22.8,
    original: 'صُمٌّ بُكْمٌ عُمْيٌ فَهُمْ لَا يَرْجِعُونَ',
    translations: {
      id: 'Mereka tuli, bisu dan buta, maka mereka tidak akan kembali',
      en: 'Deaf, dumb and blind - so they will not return [to the right path]',
      ms: 'Mereka tuli, bisu lagi buta, maka mereka tidak akan kembali',
      fr: 'Sourds, muets, aveugles, ils ne reviendront donc point',
      ur: 'بہرے ہیں، گونگے ہیں، اندھے ہیں، پس وہ واپس نہیں آئیں گے',
    },
    verseNumber: 18,
    isAiGeneratedOriginal: false,
  },
  {
    id: 5,
    start: 23.2,
    end: 29.5,
    original: 'أَوْ كَصَيِّبٍ مِّنَ السَّمَاءِ فِيهِ ظُلُمَاتٌ وَرَعْدٌ وَبَرْقٌ',
    translations: {
      id: 'Atau seperti (hujan lebat ditimpa) gelap gulita, guruh dan kilat dari langit',
      en: 'Or [it is] like a rainstorm from the sky in which is darkness, thunder and lightning',
      ms: 'Atau seperti hujan lebat dari langit, yang mengandungi kegelapan, guruh, dan kilat',
      fr: 'Ou comme une tempête de pluie venue du ciel pleine de ténèbres, tonnerre et éclairs',
      ur: 'یا جیسے آسمان سے زور دار بارش جس میں تاریکیاں، گرج اور چمک ہو',
    },
    verseNumber: 19,
    isAiGeneratedOriginal: false,
  },
  {
    id: 6,
    start: 29.8,
    end: 36.2,
    original: 'يَجْعَلُونَ أَصَابِعَهُمْ فِي آذَانِهِم مِّنَ الصَّوَاعِقِ حَذَرَ الْمَوْتِ',
    translations: {
      id: 'Mereka menyumbat telinga dengan anak jarinya karena petir, takut mati',
      en: 'They put their fingers in their ears against the thunderclaps in dread of death',
      ms: 'Mereka menyumbat jari ke dalam telinga kerana guruh yang dahsyat, takutkan mati',
      fr: 'Ils mettent leurs doigts dans leurs oreilles contre les coups de foudre, par peur de mourir',
      ur: 'وہ کڑک کی آواز سے موت کے ڈر کے مارے کانوں میں انگلیاں ٹھونس لیتے ہیں',
    },
    verseNumber: 19,
    isAiGeneratedOriginal: false,
  },
  {
    id: 7,
    start: 36.5,
    end: 42.0,
    original: 'وَاللَّهُ مُحِيطٌ بِالْكَافِرِينَ',
    translations: {
      id: 'Dan Allah meliputi orang-orang yang kafir',
      en: 'And Allah encompasses the disbelievers',
      ms: 'Dan Allah Maha Meliputi orang-orang kafir itu',
      fr: 'Et Allah cerne de tous côtés les mécréants',
      ur: 'اور اللہ کافروں کو گھیرے ہوئے ہے',
    },
    verseNumber: 19,
    isAiGeneratedOriginal: false,
  },
];

export const DEMO_PROJECT: SubtitleProject = {
  id: 'demo-quran-surah-baqarah',
  title: '',
  contentType: 'song',
  originalLanguage: 'auto',
  availableTranslations: ['id', 'en'],
  audioDuration: 0,
  audioFileName: '',
  segments: [],
  settings: {
    displayMode: 'bilingual',
    selectedTranslationLanguage: 'id',
    originalFont: 'font-arabic',
    translationFont: 'font-sans',
    originalFontSize: 44,
    translationFontSize: 22,
    originalWeight: '700',
    translationWeight: '600',
    originalColor: '#FFFFFF',
    translationColor: '#E6C86A',
    outline: true,
    shadow: true,
    lineSpacing: 14,
    position: 'center',
    alignment: 'center',
    direction: 'rtl',
    backgroundColor: 'black',
    showVerseNumber: true,
    aspectRatio: '16:9',
  },
  updatedAt: Date.now(),
};
